CREATE TABLE IF NOT EXISTS projects(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    priority INTEGER NOT NULL,
    description TEXT,
    delivery_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    project_id INTEGER REFERENCES projects(id)
);

-- Insert projects data
INSERT INTO projects(name, priority, description, delivery_date)
    VALUES('Make a web app', 1, 'Using javascript', '2021-12-20');

INSERT INTO projects(name, priority, description, delivery_date)
    VALUES('Make a mobile app', 1, 'Using dart', '2021-12-29');

INSERT INTO projects(name, priority, description, delivery_date)
    VALUES('Make a desktop app', 2, 'Using C++', '2022-01-10');

-- Insert tasks data
INSERT INTO tasks(name, done, project_id)
    VALUES('donwload Vuejs', false, 1);

INSERT INTO tasks(name, done, project_id)
    VALUES('create UI Web', false, 1);

INSERT INTO tasks(name, done, project_id)
    VALUES('download Flutter', false, 2);

INSERT INTO tasks(name, done, project_id)
    VALUES('desing UI', false, 2);